program -> statement* ;

statement      -> expressionStmt
                | varDeclarationStmt
                | assignmentStmt
                | functionStmt
                | blockStmt ;

varDeclarationStmt -> TYPE IDENTIFIER ( "=" expression )? ";" ;
expressionStmt     -> expression ";" ;
assignmentStmt     -> IDENTIFIER "=" expression ";" ;
functionStmt       -> "fn" TYPE IDENTIFIER "(" ( argument "," )* argument ")" blockStmt ;
blockStmt          -> "{" statement* "}" ;

argumentStmt -> TYPE IDENTIFIER ;

expression -> equality

equality       -> comparison ( "==" | "!=" comparison )* ;
comparison     -> addition ( ">" | ">=" | "<" | "<=") addition )* ;
addition       -> multiplication ( ( "+" | "-" ) multiplication )* ;
multiplication -> primary ( ( "*" | "/" ) primary )* ;
primary        -> NUMBER | "(" expression ")" ;

NUMBER
IDENTIFIER
TYPE -> ( "string" | "int" | "double" | "bool" ) ;
