program -> statement* ;

statement      -> expressionStmt
                | varDeclarationStmt
                | assignmentStmt ;

varDeclarationStmt -> TYPE IDENTIFIER ( "=" expression )? ";" ;
expressionStmt     -> expression ";" ;
assignmentStmt     -> IDENTIFIER "=" expression ";" ;

expression -> equality

equality       -> comparison ( "==" | "!=" comparison )* ;
comparison     -> addition ( ">" | ">=" | "<" | "<=") addition )* ;
addition       -> multiplication ( ( "+" | "-" ) multiplication )* ;
multiplication -> primary ( ( "*" | "/" ) primary )* ;
primary        -> NUMBER | "(" expression ")" ;

NUMBER
IDENTIFIER
TYPE -> ( "string" | "int" | "double" | "bool" ) ;
